/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import objetos.Claves;
import objetos.Escritor;
import objetos.Usuario;
import objetos.Usuario_b;

/**
 *
 * @author ivanc
 */
public class frmPrincipal extends javax.swing.JFrame {

    private JFrame principal;
    private Socket servidor;
    //private Usuario usuario;
    private Usuario_b usuario_b;
    private Escritor e;

    frmPrincipal(JFrame principal, Usuario_b u, Escritor e, Socket servidor) {
        initComponents();
        this.principal = principal;
        this.e = e;
        this.usuario_b = u;
        this.servidor = servidor;
        if (this.usuario_b == null) {
            btnGestionarUsuarios.setEnabled(false);
            btnGestionarUsuarios.setToolTipText("Acceso restringido");
            btnGestionarRegiones.setEnabled(false);
            btnGestionarRegiones.setToolTipText("Acceso restringido");
            btnAddIncidencias.setEnabled(false);
            btnAddIncidencias.setToolTipText("Acceso restringido");
        }else{
            if (this.usuario_b.getRol() == 2) {
            btnGestionarUsuarios.setEnabled(false);
            btnGestionarUsuarios.setToolTipText("Acceso restringido");
        }
        }
        
    }

    public frmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGestionarUsuarios = new javax.swing.JButton();
        btnGestionarRegiones = new javax.swing.JButton();
        btnConsultarDatos = new javax.swing.JButton();
        btnAddIncidencias = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MapaCovid");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/covid-19.png"))); // NOI18N

        btnGestionarUsuarios.setText("Gestionar usuarios");
        btnGestionarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarUsuariosActionPerformed(evt);
            }
        });

        btnGestionarRegiones.setText("Gestionar regiones");
        btnGestionarRegiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionarRegionesActionPerformed(evt);
            }
        });

        btnConsultarDatos.setText("Consultar datos");
        btnConsultarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarDatosActionPerformed(evt);
            }
        });

        btnAddIncidencias.setText("Añadir incidencias");
        btnAddIncidencias.setActionCommand("");
        btnAddIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddIncidenciasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGestionarRegiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnConsultarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddIncidencias, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addComponent(btnGestionarUsuarios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(67, 67, 67))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnGestionarUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGestionarRegiones, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddIncidencias, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addComponent(btnConsultarDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarDatosActionPerformed
        if (this.usuario_b == null) {
            frmConsultarIncidencias incidencias = new frmConsultarIncidencias(this, null, e, servidor);
            incidencias.setVisible(true);
            this.setVisible(false);
        } else {
            frmConsultarIncidencias incidencias = new frmConsultarIncidencias(this, usuario_b, e, servidor);
            incidencias.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnConsultarDatosActionPerformed

    private void btnAddIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddIncidenciasActionPerformed
        if (this.usuario_b == null) {
            frmAddIncidencias incidencias = new frmAddIncidencias(this, null, e, servidor);
            incidencias.setVisible(true);
            this.setVisible(false);
        } else {
            frmAddIncidencias incidencias = new frmAddIncidencias(this, usuario_b, e, servidor);
            incidencias.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnAddIncidenciasActionPerformed

    private void btnGestionarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarUsuariosActionPerformed
        if (this.usuario_b == null) {
            frmUsuarios usuarios = new frmUsuarios(this, null, e, servidor);
            usuarios.setVisible(true);
            this.setVisible(false);
        } else {
            frmUsuarios usuarios = new frmUsuarios(this, usuario_b, e, servidor);
            usuarios.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnGestionarUsuariosActionPerformed

    private void btnGestionarRegionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionarRegionesActionPerformed

        if (this.usuario_b == null) {
            frmRegiones regiones = new frmRegiones(this, null, e, servidor);
            regiones.setVisible(true);
            this.setVisible(false);
        } else {
            frmRegiones regiones = new frmRegiones(this, usuario_b, e, servidor);
            regiones.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnGestionarRegionesActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            e.escribir(false);
            servidor.close();
        } catch (Exception ex) {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddIncidencias;
    private javax.swing.JButton btnConsultarDatos;
    private javax.swing.JButton btnGestionarRegiones;
    private javax.swing.JButton btnGestionarUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
