/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import ayuda.Constantes;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import objetos.Escritor;
import objetos.Region;
import objetos.Usuario;
import objetos.Usuario_b;

/**
 *
 * @author ivanc
 */
public class frmRegiones extends javax.swing.JFrame {

    private JFrame principal;
    private Socket servidor;
    //private Usuario usuario;
    private Usuario_b usuario;
    private Escritor e;
    String nombre;

    public frmRegiones(JFrame principal, Usuario_b usuario, Escritor e, Socket servidor) {
        initComponents();
        this.principal = principal;
        this.servidor = servidor;
        this.usuario = usuario;
        this.e = e;
    }

    /**
     * Creates new form frmRegiones
     */
    public frmRegiones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegiones = new javax.swing.JTable();
        btnAddRegion = new javax.swing.JButton();
        txtNombreRegion = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnEliminarRegion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Regiones");
        setMaximumSize(new java.awt.Dimension(343, 438));
        setSize(new java.awt.Dimension(343, 448));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(343, 428));
        jPanel2.setMinimumSize(new java.awt.Dimension(343, 428));
        jPanel2.setPreferredSize(new java.awt.Dimension(343, 448));

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tblRegiones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Region"
            }
        ));
        tblRegiones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRegionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRegiones);

        btnAddRegion.setText("Añadir");
        btnAddRegion.setToolTipText("");
        btnAddRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddRegionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Nombre de la región");

        btnEliminarRegion.setText("Eliminar");
        btnEliminarRegion.setToolTipText("");
        btnEliminarRegion.setEnabled(false);
        btnEliminarRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarRegionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(126, 126, 126))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(txtNombreRegion, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(jLabel1))))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btnAddRegion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEliminarRegion)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtNombreRegion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddRegion)
                    .addComponent(btnEliminarRegion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVolver)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (this.usuario == null) {
            frmPrincipal principal = new frmPrincipal(this, null, e, servidor);
            principal.setVisible(true);
            this.setVisible(false);
        } else {
            frmPrincipal principal = new frmPrincipal(this, usuario, e, servidor);
            principal.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAddRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddRegionActionPerformed
        if (!txtNombreRegion.getText().isEmpty()) {
            try {
                nombre = txtNombreRegion.getText();
                e.escribir(true);
                e.escribir(Constantes.ADD_REGION);
                nombre = txtNombreRegion.getText();
                Region r = new Region(nombre);
                e.escribir(r);
                if ((boolean) e.leer()) {
                    JOptionPane.showMessageDialog(null, "Región registrada con exito!");
                    limpiarTabla();
                    cargarRegiones();
                }
            } catch (Exception ex) {
                Logger.getLogger(frmRegiones.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Rellene todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddRegionActionPerformed

    private void btnEliminarRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarRegionActionPerformed
        try {
            DefaultTableModel tm = (DefaultTableModel) tblRegiones.getModel();
            String nombreRegion = String.valueOf(tm.getValueAt(tblRegiones.getSelectedRow(), 1));
            e.escribir(true);
            e.escribir(Constantes.BORRAR_REGION);
            e.escribir(nombreRegion);
            JOptionPane.showMessageDialog(null, "Usuario eliminado");
            limpiarTabla();
            cargarRegiones();
        } catch (Exception e) {
            Logger.getLogger(frmRegiones.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_btnEliminarRegionActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        try {
            cargarRegiones();
        } catch (Exception ex) {
            Logger.getLogger(frmRegiones.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formComponentShown

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            e.escribir(false);
            servidor.close();
        } catch (Exception ex) {
            Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowClosed

    private void tblRegionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRegionesMouseClicked
        DefaultTableModel tm = (DefaultTableModel) tblRegiones.getModel();
        String fila = String.valueOf(tm.getValueAt(tblRegiones.getSelectedRow(), 0));
        if (!fila.equals("null")) {
            btnEliminarRegion.setEnabled(true);
            btnEliminarRegion.setEnabled(true);
        } else {
            btnEliminarRegion.setEnabled(false);
            btnEliminarRegion.setEnabled(false);
        }
    }//GEN-LAST:event_tblRegionesMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddRegion;
    private javax.swing.JButton btnEliminarRegion;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRegiones;
    private javax.swing.JTextField txtNombreRegion;
    // End of variables declaration//GEN-END:variables

    private void cargarRegiones() throws Exception {
        DefaultTableModel tm = (DefaultTableModel) tblRegiones.getModel();
        e.escribir(true);
        e.escribir(Constantes.CARGAR_REGIONES);
        int fila = 0;
        limpiarTabla();
        while ((boolean) e.leer()) {
            Region r = (Region) e.leer();
            tm.addRow(new Object[1]);
            addRegion(r, fila);
            fila++;
        }
    }

    private void limpiarTabla() {
        DefaultTableModel tb = (DefaultTableModel) tblRegiones.getModel();
        int a = tblRegiones.getRowCount() - 1;
        for (int i = a; i >= 0; i--) {
            tb.removeRow(tb.getRowCount() - 1);
        }
    }

    private void addRegion(Region r, int fila) {
        tblRegiones.setValueAt(fila + 1, fila, 0);
        tblRegiones.setValueAt(r.getRegion(), fila, 1);
    }
}
